name: onzek
description: A new Flutter project.



publish_to: 'none'





version: 1.0.0+1



environment:
  sdk: '>=2.18.0 <3.0.0'




dependencies:
  flutter:
    sdk: flutter





  cupertino_icons: ^1.0.2
  grouped_list: ^5.1.2
  intl: ^0.17.0
  image_picker: ^0.8.6
  firebase_auth: ^4.0.2
  firebase_database: ^10.0.2
  firebase_storage: ^11.0.2
  cached_network_image: ^3.2.2
  google_sign_in: ^5.4.2
  getwidget: ^3.0.1
  

  
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.11
  flutter_launcher_icons: ^0.10.0




flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/Iconeapp.png"




flutter_native_splash:
  color: "#f9f9f9"
  image: "assets/images/logo.png"
  flutter_lints: ^2.0.0




flutter:
  uses-material-design: true


  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
